### ISSUE TITLE
Erro GRUPO.json e nome do repositório

### ISSUE THREAD

**Issue by rafaelcorsi** [pedr0luiz/Z01.1-Hardware#29]
https://github.com/pedr0luiz/Z01.1-GrupoH/blob/042298d3f6bb142a4a1fbd7f58604024861d2fb5/GRUPO.json#L1

Scrum Master corrigi esse erro de merge!!! Vocês devem renomear o nome do repositório para o nome do grupo: Z01.1-Hardware

**Comment by gabrielzezze** [comment]
Okk, nome ja foi alterado.
